// React/src/orig_App.js
import './App.css';
import 'devextreme/dist/css/dx.light.css';

import React, { useCallback, useEffect, useRef, useState } from "react";
import DropDownBox from "devextreme-react/drop-down-box";
import TreeView from "devextreme-react/tree-view";
import TagBox from "devextreme-react/tag-box";
import TextBox from "devextreme-react/text-box";
import CustomStore from "devextreme/data/custom_store";
import "whatwg-fetch";
import Popup from "devextreme/ui/popup";

const dropDownBoxAttributes = {
  id: "myDropDownBox"
};

const treeDataSource = new CustomStore({
  loadMode: "raw",
  key: "ID",
  load() {
    return fetch(
      `https://js.devexpress.com/Demos/WidgetsGallery/JSDemos/data/treeProducts.json`
    ).then((response) => response.json());
  }
});

const renderTagBox = (treeBoxValue, setTreeBoxValue) => () => {
  const onValueChanged = useCallback(({ value }) => {
    setTreeBoxValue(value);
  }, []);

  return (<div>
    <TextBox visible={false} />
    <TagBox
      dataSource={treeDataSource}
      value={treeBoxValue}
      valueExpr="ID"
      displayExpr="name"
      onValueChanged={onValueChanged}
      openOnFieldClick={false}
      placeholder="Select a value..."
      showClearButton={true}
      width="100%"
    />
  </div>);
};

export default function App() {
  const treeView = useRef(null);
  const [treeBoxValue, setTreeBoxValue] = useState(["1_1"]);

  const onContentReady = useCallback(({ component }) => {
    if (!component.isNotFirstLoad && treeBoxValue) {
      component.isNotFirstLoad = true;
      treeBoxValue.forEach((item) => {
        component.selectItem(item);
      });
    }
  }, [treeBoxValue]);
  

  const onSelectionChanged = useCallback(({ component }) => {
    let keys = component.getSelectedNodeKeys();

    if (!component.customSelection && JSON.stringify(treeBoxValue) !== JSON.stringify(keys)) {
      setTreeBoxValue(keys);
    }
  }, [treeBoxValue]);

  const onValueChanged = useCallback(({ value }) => {
    setTreeBoxValue(value);
  }, []);

  useEffect(() => {
    const treeViewInstance = treeView?.current?.instance;

    // Synchronize TreeView
    if (!treeViewInstance) return;
    treeViewInstance.customSelection = true;
    treeViewInstance.unselectAll();
    if (treeBoxValue && treeBoxValue.length > 0) {
      treeBoxValue.forEach((item) => {
        treeViewInstance.selectItem(item);
      });
    }
    treeViewInstance.customSelection = false;

    var popup = Popup.getInstance(
      document.querySelector("#myDropDownBox .dx-dropdowneditor-overlay")
    );
    setTimeout(() => popup.repaint());
  }, [treeView, treeBoxValue]);

  return (
    <div className="dx-fieldset">
      <div className="dx-field">
        <div className="dx-field-label">DropDownBox with embedded TreeView</div>
        <div className="dx-field-value">
          <DropDownBox
            elementAttr={dropDownBoxAttributes}
            deferRendering={false}
            value={treeBoxValue}
            valueExpr="ID"
            displayExpr="name"
            dataSource={treeDataSource}
            fieldComponent={renderTagBox(treeBoxValue, setTreeBoxValue)}
            onValueChanged={onValueChanged}
          >
            <TreeView
              ref={treeView}
              onContentReady={onContentReady}
              dataSource={treeDataSource}
              dataStructure="plain"
              keyExpr="ID"
              parentIdExpr="categoryId"
              selectionMode="multiple"
              showCheckBoxesMode="normal"
              selectNodesRecursive={false}
              displayExpr="name"
              selectByClick={true}
              onItemSelectionChanged={onSelectionChanged}
            />
          </DropDownBox>
        </div>
      </div>
    </div>
  );
}

// Angular/src/app/orig_app.component.ts
import {
  Component,
  ViewChild,
} from "@angular/core";
import { HttpClient } from "@angular/common/http";

import CustomStore from "devextreme/data/custom_store";
import { DxTreeViewComponent } from "devextreme-angular";
import Popup from "devextreme/ui/popup";

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  @ViewChild(DxTreeViewComponent, { static: false }) treeView: DxTreeViewComponent;
  treeDataSource: any;
  treeBoxValue: string[];
  
  constructor(private httpClient: HttpClient) {
    this.treeDataSource = this.makeAsyncDataSource(this.httpClient, 'treeProducts.json');
    this.treeBoxValue = ['1_1', '1_1_1'];
  }

  makeAsyncDataSource(http: HttpClient, jsonFile: string) {
    return new CustomStore({
      loadMode: "raw",
      key: "ID",
      load(): Promise<any> {
        return http
          .get(
            `https://js.devexpress.com/Demos/WidgetsGallery/JSDemos/data/${jsonFile}`
          )
          .toPromise();
      }
    });
  }

  onDropDownBoxValueChanged(e: any) {
    this.updateSelection(this.treeView && this.treeView.instance);
  }

  onTreeViewReady(e: any) {
    this.updateSelection(e.component);
  }

  updateSelection(treeView: any) {
    if (!treeView) return;
    
    if (!this.treeBoxValue) {
      treeView.unselectAll();
    }

    if (this.treeBoxValue) {
      this.treeBoxValue.forEach(((value) => {
        treeView.selectItem(value);
      }));
    }

    let element = document.querySelector("#myDropDownBox .dx-dropdowneditor-overlay");
    if (element) {
      let popup = Popup.getInstance(element) as Popup,
        scrollable = treeView.getScrollable(),
        scrollTop = scrollable.scrollTop();
        popup.repaint();
        scrollable.scrollTo(scrollTop);
    }
  }

  onTreeViewSelectionChanged(e: any) {
    this.treeBoxValue = e.component.getSelectedNodeKeys();
  }

  onTagBoxValueChanged(e: any) {
    if (!this.treeView) return;
    this.treeView.instance.unselectAll();
    this.updateSelection(this.treeView.instance);
  }
}

<div class="dx-fieldset">
  <div class="dx-field">
    <div class="dx-field-label">DropDownBox with embedded TreeView</div>
    <div class="dx-field-value">
      <dx-drop-down-box
        ID="myDropDownBox"
        [(value)]="treeBoxValue"
        valueExpr="ID"
        displayExpr="name"
        [dataSource]="treeDataSource"
        (onValueChanged)="onDropDownBoxValueChanged($event)"
        fieldTemplate="fieldTemplate"
        [showClearButton]="true"
      >
        <div *dxTemplate="let info of 'fieldTemplate'">
          <dx-text-box [visible]="false"></dx-text-box>
          <dx-tag-box
            [dataSource]="treeDataSource"
            [(value)]="treeBoxValue"
            valueExpr="ID"
            displayExpr="name"
            placeholder="Select a value..."
            [openOnFieldClick]="false"
            width="100%"
            (onValueChanged)="onTagBoxValueChanged($event)"
          >
          </dx-tag-box>
        </div> 
        <div *dxTemplate="let data of 'content'">
          <dx-tree-view
          #treeView
            [dataSource]="treeDataSource"
            dataStructure="plain"
            keyExpr="ID"
            parentIdExpr="categoryId"
            selectionMode="multiple"
            showCheckBoxesMode="normal"
            [selectNodesRecursive]="false"
            displayExpr="name"
            [selectByClick]="true"
            (onContentReady)="onTreeViewReady($event)"
            (onItemSelectionChanged)="onTreeViewSelectionChanged($event)"
            >
          </dx-tree-view>
        </div>
      </dx-drop-down-box>
    </div>
  </div>
</div>
